// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorreLogistica.Infrastructure.Persistencia;

#nullable disable

namespace TorreLogistica.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(TorreLogisticaDbContext))]
    [Migration("20260914122449_Identidade")]
    partial class Identidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorreLogistica.Domain.Auditoria.EventoDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlvoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_id");

                    b.Property<string>("AlvoTipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("alvo_tipo");

                    b.Property<Guid?>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("Dados")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_eventos_de_auditoria");

                    b.HasIndex("OrganizacaoId", "OcorridoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eventos_de_auditoria_organizacao_id_ocorrido_em");

                    b.ToTable("eventos_de_auditoria", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizacoes_slug");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revogada_em");

                    b.Property<DateTimeOffset>("UltimaRenovacaoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_renovacao_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_sessoes_organizacao_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessoes_usuario_id_abertas")
                        .HasFilter("revogada_em IS NULL");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.TokenDeRenovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EmitidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("emitido_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<byte[]>("HashDoToken")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_do_token");

                    b.Property<DateTimeOffset?>("InvalidadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("invalidado_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<Guid?>("SubstitutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituto_id");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("usado_em");

                    b.HasKey("Id")
                        .HasName("pk_tokens_de_renovacao");

                    b.HasIndex("HashDoToken")
                        .IsUnique()
                        .HasDatabaseName("ux_tokens_de_renovacao_hash_do_token");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_tokens_de_renovacao_sessao_id");

                    b.ToTable("tokens_de_renovacao", null, t =>
                        {
                            t.HasCheckConstraint("ck_tokens_de_renovacao_hash_tem_32_bytes", "octet_length(hash_do_token) = 32");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_normalizado");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("perfil");

                    b.Property<int>("TentativasDeLoginFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_de_login_falhas");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("OrganizacaoId", "EmailNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_organizacao_id_email_normalizado");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_tentativas_de_login_falhas_nao_negativas", "tentativas_de_login_falhas >= 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Auditoria.EventoDeAuditoria", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_de_auditoria_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Sessao", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_organizacoes_organizacao_id");

                    b.HasOne("TorreLogistica.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_usuarios_usuario_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.TokenDeRenovacao", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Sessao", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_de_renovacao_sessoes_sessao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });
#pragma warning restore 612, 618
        }
    }
}
