// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorreLogistica.Infrastructure.Persistencia;

#nullable disable

namespace TorreLogistica.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(TorreLogisticaDbContext))]
    [Migration("20260914182612_Entregas")]
    partial class Entregas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorreLogistica.Domain.Auditoria.EventoDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlvoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_id");

                    b.Property<string>("AlvoTipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("alvo_tipo");

                    b.Property<Guid?>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("Dados")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_eventos_de_auditoria");

                    b.HasIndex("OrganizacaoId", "OcorridoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eventos_de_auditoria_organizacao_id_ocorrido_em");

                    b.ToTable("eventos_de_auditoria", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("OrganizacaoId", "Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_organizacao_id_cnpj")
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("OrganizacaoId", "NomeNormalizado")
                        .HasDatabaseName("ix_clientes_organizacao_id_nome_normalizado");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Clientes.Destinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("InstrucoesDeEntrega")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("instrucoes_de_entrega");

                    b.Property<Point>("Localizacao")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("telefone");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Endereco", "TorreLogistica.Domain.Clientes.Destinatario.Endereco#Endereco", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character(8)")
                                .HasColumnName("endereco_cep")
                                .IsFixedLength();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("endereco_uf")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_destinatarios");

                    b.HasIndex("Localizacao")
                        .HasDatabaseName("ix_destinatarios_localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "gist");

                    b.HasIndex("OrganizacaoId", "NomeNormalizado")
                        .HasDatabaseName("ix_destinatarios_organizacao_id_nome_normalizado");

                    b.ToTable("destinatarios", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Entregas.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizada_em");

                    b.Property<DateTimeOffset?>("CanceladaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelada_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criada_em");

                    b.Property<string>("DescricaoDoCancelamento")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("descricao_do_cancelamento");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinatario_id");

                    b.Property<Point>("Localizacao")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("localizacao");

                    b.Property<string>("MotivoDoCancelamento")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_do_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("UltimaSequenciaDeEvento")
                        .HasColumnType("integer")
                        .HasColumnName("ultima_sequencia_de_evento");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Endereco", "TorreLogistica.Domain.Entregas.Entrega.Endereco#Endereco", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character(8)")
                                .HasColumnName("endereco_cep")
                                .IsFixedLength();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("endereco_uf")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Janela", "TorreLogistica.Domain.Entregas.Entrega.Janela#JanelaDeEntrega", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Fim")
                                .HasColumnType("timestamptz")
                                .HasColumnName("prometida_ate");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamptz")
                                .HasColumnName("prometida_de");
                        });

                    b.HasKey("Id")
                        .HasName("pk_entregas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_entregas_cliente_id");

                    b.HasIndex("DestinatarioId")
                        .HasDatabaseName("ix_entregas_destinatario_id");

                    b.HasIndex("Localizacao")
                        .HasDatabaseName("ix_entregas_localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "gist");

                    b.HasIndex("OrganizacaoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_entregas_organizacao_id_codigo");

                    b.ToTable("entregas", null, t =>
                        {
                            t.HasCheckConstraint("ck_entregas_janela_prometida_ordenada", "prometida_ate > prometida_de");

                            t.HasCheckConstraint("ck_entregas_ultima_sequencia_de_evento_positiva", "ultima_sequencia_de_evento > 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Entregas.EventoDaEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("Dados")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entrega_id");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer")
                        .HasColumnName("sequencia");

                    b.Property<string>("StatusResultante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_resultante");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_eventos_da_entrega");

                    b.HasIndex("AutorUsuarioId")
                        .HasDatabaseName("ix_eventos_da_entrega_autor_usuario_id");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_eventos_da_entrega_organizacao_id");

                    b.HasIndex("EntregaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("ux_eventos_da_entrega_entrega_id_sequencia");

                    b.ToTable("eventos_da_entrega", null, t =>
                        {
                            t.HasCheckConstraint("ck_eventos_da_entrega_sequencia_positiva", "sequencia > 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Frota.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("telefone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_motoristas");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_motoristas_usuario_id")
                        .HasFilter("usuario_id IS NOT NULL");

                    b.HasIndex("OrganizacaoId", "NomeNormalizado")
                        .HasDatabaseName("ix_motoristas_organizacao_id_nome_normalizado");

                    b.ToTable("motoristas", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Frota.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CapacidadeEmKg")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_em_kg");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("identificacao");

                    b.Property<string>("IdentificacaoNormalizada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("identificacao_normalizada");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("placa")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("OrganizacaoId", "Placa")
                        .IsUnique()
                        .HasDatabaseName("ux_veiculos_organizacao_id_placa");

                    b.ToTable("veiculos", null, t =>
                        {
                            t.HasCheckConstraint("ck_veiculos_capacidade_em_kg_positiva", "capacidade_em_kg IS NULL OR capacidade_em_kg > 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizacoes_slug");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadaEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revogada_em");

                    b.Property<DateTimeOffset>("UltimaRenovacaoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_renovacao_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_sessoes_organizacao_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessoes_usuario_id_abertas")
                        .HasFilter("revogada_em IS NULL");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.TokenDeRenovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EmitidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("emitido_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<byte[]>("HashDoToken")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_do_token");

                    b.Property<DateTimeOffset?>("InvalidadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("invalidado_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<Guid?>("SubstitutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituto_id");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("usado_em");

                    b.HasKey("Id")
                        .HasName("pk_tokens_de_renovacao");

                    b.HasIndex("HashDoToken")
                        .IsUnique()
                        .HasDatabaseName("ux_tokens_de_renovacao_hash_do_token");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_tokens_de_renovacao_sessao_id");

                    b.ToTable("tokens_de_renovacao", null, t =>
                        {
                            t.HasCheckConstraint("ck_tokens_de_renovacao_hash_tem_32_bytes", "octet_length(hash_do_token) = 32");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_normalizado");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("perfil");

                    b.Property<int>("TentativasDeLoginFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_de_login_falhas");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("OrganizacaoId", "EmailNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_organizacao_id_email_normalizado");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_tentativas_de_login_falhas_nao_negativas", "tentativas_de_login_falhas >= 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Operacao.Hub", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Endereco", "TorreLogistica.Domain.Operacao.Hub.Endereco#Endereco", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character(8)")
                                .HasColumnName("endereco_cep")
                                .IsFixedLength();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("endereco_uf")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_hubs");

                    b.HasIndex("Localizacao")
                        .HasDatabaseName("ix_hubs_localizacao");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Localizacao"), "gist");

                    b.HasIndex("OrganizacaoId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_hubs_organizacao_id_nome_normalizado");

                    b.ToTable("hubs", (string)null);
                });

            modelBuilder.Entity("TorreLogistica.Infrastructure.Persistencia.Configuracoes.SequenciaDeCodigo", b =>
                {
                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Serie")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("serie");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("OrganizacaoId", "Serie", "Ano")
                        .HasName("pk_sequencias_de_codigo");

                    b.ToTable("sequencias_de_codigo", null, t =>
                        {
                            t.HasCheckConstraint("ck_sequencias_de_codigo_ultimo_numero_positivo", "ultimo_numero > 0");
                        });
                });

            modelBuilder.Entity("TorreLogistica.Domain.Auditoria.EventoDeAuditoria", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_de_auditoria_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Clientes.Destinatario", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_destinatarios_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Entregas.Entrega", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_clientes_cliente_id");

                    b.HasOne("TorreLogistica.Domain.Clientes.Destinatario", null)
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_destinatarios_destinatario_id");

                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Entregas.EventoDaEntrega", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_eventos_da_entrega_usuarios_autor_usuario_id");

                    b.HasOne("TorreLogistica.Domain.Entregas.Entrega", null)
                        .WithMany()
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_da_entrega_entregas_entrega_id");

                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_da_entrega_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Frota.Motorista", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_motoristas_organizacoes_organizacao_id");

                    b.HasOne("TorreLogistica.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_motoristas_usuarios_usuario_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Frota.Veiculo", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Sessao", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_organizacoes_organizacao_id");

                    b.HasOne("TorreLogistica.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_usuarios_usuario_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.TokenDeRenovacao", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Sessao", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_de_renovacao_sessoes_sessao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Domain.Operacao.Hub", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hubs_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("TorreLogistica.Infrastructure.Persistencia.Configuracoes.SequenciaDeCodigo", b =>
                {
                    b.HasOne("TorreLogistica.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sequencias_de_codigo_organizacoes_organizacao_id");
                });
#pragma warning restore 612, 618
        }
    }
}
